plugins {
    id "java-library"
    id "maven-publish"

    id "ru.vyarus.animalsniffer"
}

description = 'gRPC: Census'

evaluationDependsOn(project(':grpc-api').path)
evaluationDependsOn(project(':grpc-core').path)

dependencies {
    api project(':grpc-api')
    implementation libraries.guava,
            libraries.opencensus.api,
            libraries.opencensus.contrib.grpc.metrics
    implementation ('io.opentelemetry:opentelemetry-api:1.24.0')
    implementation ('io.opentelemetry:opentelemetry-sdk:1.24.0')
    implementation 'com.google.cloud.opentelemetry:exporter-trace:0.15.0'
    implementation ('io.opentelemetry:opentelemetry-exporter-logging:1.24.0')

    testImplementation testFixtures(project(':grpc-api')),
            testFixtures(project(':grpc-context')),
            testFixtures(project(':grpc-core')),
            project(':grpc-testing'),
            libraries.opencensus.impl

    signature libraries.signature.java
    signature libraries.signature.android
}

tasks.named("javadoc").configure {
    failOnError false  // no public or protected classes found to document
    exclude 'io/grpc/census/internal/**'
    exclude 'io/grpc/census/Internal*'
}
